### ISSUE TITLE
"Callback URL is empty" error on subscription creation

### ISSUE THREAD

**Issue by bqmackay** [Bandwidth/ruby-bandwidth-iris#16]
I'm trying to create a subscription to listen for order callbacks. After following the instructions from the [API guide](https://dev.bandwidth.com/numbers/guides/onDemandNumberSearchAndOrder.html#create-subscription) and this repo's README, I have come up with the following Subscription data structure and call to create a subscription:

```
subscription_data = {
        order_type: "orders",
        callback_subscription: {
          url: "https://#{ENV.fetch("HOST")}/bandwidth/orders",
          callback_credentials: {
            basic_authentication: {
              username: "#{ENV.fetch("BANDWIDTH_V2_CALLBACK_USERNAME")}",
              password: "#{ENV.fetch("BANDWIDTH_V2_CALLBACK_PASSWORD")}",
            }
          },
          expiry: 12000
        }
      }
subscription = BandwidthIris::Subscription.create(subscription_data)
```

The error it gives me is `BandwidthIris::Errors::GenericError: Callback URL is empty`. The url is there and, according to the documentation, it's in the right spot (unless I'm missing something obvious). Any ideas what the error may be referring to or what my data structure may be missing?

**Comment by bqmackay** [comment]
After some more trial-and-error, the `url` key needs to be in all caps (`URL`). It seems like that shouldn't be the case, but if it is required, I recommend updating the README to reflect that requirement.

**Comment by bqmackay** [comment]
PR to update the readme: https://github.com/Bandwidth/ruby-bandwidth-iris/pull/17

**Comment by bqmackay** [comment]
@jmulford-bw Just making sure you're pinged on this. See PR link above

**Comment by jmulford-bw** [comment]
👍
