### ISSUE TITLE
BandwidthIris::SipPeer.get(sip_peer_id) returns an ArgumentError

### ISSUE THREAD

**Issue by bqmackay** [Bandwidth/ruby-bandwidth-iris#19]
When I attempt to get a specific SipPeer by calling:
```
BandwidthIris::SipPeer.get(sip_peer_id)
```
 I get the following error:
```
ArgumentError: wrong number of arguments (given 2, expected 3)
from /Users/byron/.rvm/gems/ruby-2.6.5/gems/ruby-bandwidth-iris-1.0.2/lib/bandwidth-iris/sip_peer.rb:13:in `get'
```

**Comment by jmulford-bw** [comment]
Hey @bqmackay it looks like the README is incorrect. Try passing in the site id that the sippeer sites under, then the sippeer id like

```
BandwidthIris::SipPeer.get(site_id, sip_peer_id)
```

We'll do a bulk update of the README to fix these inconsistencies.

**Comment by jmulford-bw** [comment]
Also I noticed you're on version 1.0.2 of the gem. You may want to update to at least 1.0.5

**Comment by bradeaton** [comment]
I had also encountered this problem. Your README also indicates that BandwidthIris::SipPeer.get(site_id, sip_peer_id) returns a sipPeer object that you could then to a sipPeer.update_tns(number, tns). But, it seems that it returns a hash instead. What is the method that returns a sipPeer object?

**Comment by dtolb** [comment]
@bradeaton still digging through a lot (specifically tn options), but you're correct in that the readme alludes that a `SIPPEER` object is returned with attached methods.

However, the SDK does not actually return such object. I believe that the work here (for @Bandwidth/dx ) is to clean up the readme to match actual behavior vs update the source code to result in breaking changes.

Here is some sample source that creates a SIPPEER then deletes it.

```ruby
require 'ruby-bandwidth-iris'
SITE_ID = "{YOUR_SITE_ID}"
BandwidthIris::Client.global_options = {
  :api_endpoint => "https://dashboard.bandwidth.com/api",
  :user_name => ENV.fetch("BANDWIDTH_API_USER"),
  :password => ENV.fetch("BANDWIDTH_API_PASSWORD"),
  :account_id => ENV.fetch("BANDWIDTH_ACCOUNT_ID")
}
data = {
    :peer_name => "A New SIP Peer",
    :is_default_peer => false
}
myNewSipPeer = BandwidthIris::SipPeer.create(SITE_ID, data)
puts myNewSipPeer[:id]
mySipPeerObject =  BandwidthIris::SipPeer.new({
                                                 :site_id => SITE_ID,
                                                 :id => myNewSipPeer[:id]
                                             })
puts mySipPeerObject.delete()
```

Note the _manual_ creation of the SIPPEER object.  This gives you access to the methods you'll need to delete / moveTns / etc...

Closing this specifically in favor of [21](https://github.com/Bandwidth/ruby-bandwidth-iris/issues/21)

Thx for bringing this up!
