### ISSUE TITLE
Order a phone - polling approach 

### ISSUE THREAD

**Issue by eftikharEmad** [Bandwidth/ruby-bandwidth-iris#22]
Hello team, 

I am searching for an example on ordering a phone with a polling approach, is there any ?
https://dev.bandwidth.com/numbers/guides/numberOrderingSummary.html#order-phone-numbers

hope you can help me.
thanks

**Comment by jmulford-bw** [comment]
The code sample on the bottom of https://dev.bandwidth.com/sdks/ruby.html shows you how to create an order, and then fetch the order information. Does that answer your question?

**Comment by eftikharEmad** [comment]
hello @jmulford-bw ,

thank you for reply, I read the link you shared but thats was not what I am looking for, after reading the docs I found it finally here:
https://dev.bandwidth.com/numbers/apiReference.html
`
<AreaCodeSearchAndOrderType>
    <AreaCode>617</AreaCode> 
    <Quantity>1</Quantity> 
</AreaCodeSearchAndOrderType>
`
use order type `AreaCodeSearchAndOrderType` that way I don't have to wait the call back :) 
sorry for my late response.
I will close it 👍
