### ISSUE TITLE
Feature: cancel not completed order

### ISSUE THREAD

**Issue by eftikharEmad** [Bandwidth/ruby-bandwidth-iris#37]
Is there a way to cancel an order is in pending status ?

**Comment by jmulford-bw** [comment]
Hi @eftikharEmad,

You should be able to update an order with the body value `:close_order` set to `true`. This will cancel the request if the order hasn't been completed.

Our full API reference can be found at https://dev.bandwidth.com/numbers/apiReference.html if that helps!

**Comment by eftikharEmad** [comment]
yes it helps a lot thank you so much.
I didn't notice it before

**Comment by eftikharEmad** [comment]
hello @jmulford-bw 
I have question based on this documentation https://dev.bandwidth.com/numbers/guides/numberOrderingSummary.html#order-phone-numbers 
as I mentioned before I trying to close a `Pending` order (for some reason), so I am getting this error 
```BandwidthIris::Errors::GenericError: Only Backordered order can be closed``` for failed and completed orders 

the order simply created by this flow 
```
   order = BandwidthIris::Order.create(order_data)
   order_details = order.get_tns 
   ......
  (try to wait order to be completed/failed) if order_details.blank?
   order&.update(close_order: true)    # if order still pending I need to close it
```

now the order is created with `BackOrderRequested = false` as a default value, so is it a valid method for pending orders ??

**Comment by ajrice6713** [comment]
Hi @eftikharEmad, 

This sounds more like a bug on our backend, and not so much with the SDK, if it is the same order from the issue a few days ago. How long are you waiting in between placing the order and attempting to cancel it? Would it be possible for you to open a support ticket via support.bandwidth.com so that we can troubleshoot a little further and get some of those OrderID's?

**Comment by eftikharEmad** [comment]
Hello @ajrice6713 , Thank you for replying.
some orders take up to 30 sec (the max value I noticed), but I am trying to wait for max (6 sec) until the data is being available , otherwise I need to cancel the order.

this case happened twice today .

I will try to open a ticket 🙂 , thanks again.

**Comment by ajrice6713** [comment]
Hey @eftikharEmad,

Feel free to provide me with that ticket number and I will follow up there!

**Comment by eftikharEmad** [comment]
hello @ajrice6713 
here is the ticket number #3704718, waiting your feedback 🙂
