### ISSUE TITLE
Incorrect information in Readme

### ISSUE THREAD

**Issue by EvanDaley** [Bandwidth/ruby-bandwidth-iris#41]
Under "Sites" you have the string "A site is what is called Location in the web UI" but I believe that this is incorrect. A **site** is a **subaccount** and a **peer_id** is a **location in web ui.**

As a concrete example, when I order a phone number: SUBACCOUNT goes into site_id and LOCATION goes into peer_id.
```
        @order_response = BandwidthIris::Order.create(
            {
                name: "Customer order",
                site_id: BANDWIDTH_SUB_ACCOUNT_ID,
                peer_id: BANDWIDTH_LOCATION_ID,
                existing_telephone_number_order_type: {
                    telephone_number_list: {
                        telephone_number: [@data['number']]
                    }
                }
            })
```

**Comment by ajrice6713** [comment]
Hey Evan,

Thanks for pointing out that inconsistency - the readme has been updated to reflect  the correct information!
