### ISSUE TITLE
Does this gem only work with ActiveSupport 4.2.7?

### ISSUE THREAD

**Issue by steventwheeler** [Bandwidth/ruby-bandwidth-iris#7]
The [gemspec](https://github.com/Bandwidth/ruby-bandwidth-iris/blob/master/ruby-bandwidth-iris.gemspec#L20) lists this dependency:

```ruby
  spec.add_dependency "activesupport","4.2.7"
```

This means that the gem can only be used with [rails 4.2.7](https://rubygems.org/gems/rails/versions/4.2.7) which was released back in 2016. This dependency is preventing us from using versions above 1.0.2 of this gem in our application.

**Comment by jmulford-bw** [comment]
Hey @steventwheeler I'm so sorry for not updating you on this. This is no longer the case, the dependency is now `">= 4.2.7"`
